name: Call Packaging Workflow

on:
    push

jobs:
    call-packaging:
        uses: AntonioFigueiredo/PackagingDebRpm/.github/workflows/packaging.yml@main
        secrets: inherit
        with:
            project_name: plxsdk
            build_rpm: false
            build_deb: false
            sign_packages: true
            
            deb_matrix: '{"container":["debian:stable","debian:bullseye","debian:unstable","debian:testing"]}'
            rpm_matrix: '{"container":["rockylinux:9"]}'